apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30261   # Force nodePort same if you want
