apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==   # base64 of mongoadmin
  mongo-root-password: bW9uZ29wYXNzd29yZA== # base64 of mongopassword
